services:
    # WordPress
    wordpress:
        image: wordpress:6.8-php8.2-apache
        ports:
            - "80:80"
        environment:
            WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
            WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
            WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
            - ./wordpress:/var/www/html
            - .env:/var/www/html/.env
        depends_on:
            - db_rekrutacja

    # MySQL
    db_rekrutacja:
        image: mariadb:10.6-focal
        platform: linux/amd64
        environment:
            MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
            MYSQL_USER: ${WORDPRESS_DB_USER}
            MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql

    # phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8089:80"
        environment:
            PMA_HOST: db_rekrutacja
        depends_on:
            - db_rekrutacja

volumes:
    db_data: {}
